### ISSUE TITLE
Missing functions from readme, indexing instructions

### ISSUE THREAD

**Issue by darkseed** [usc-isi-i2/elasticsearch-image-features#1]
Hi,

Looking at your code, and wanted to add image features to ES.
But there seen to be missing some features from the README for indexing the features in ES.

I'm curious to what LireImage does with the features, how it serializes the features in the json.
I'm assuming an double array serialized as base64?

And Utils.executeProcess is missing (but i can imagine what this does).

**Comment by szeke** [comment]
Lakshmi

Can u answer this question?

p

**Comment by kasinath** [comment]
Hi Tom!

LireImage is just a simple POJO that contains the data (name of the file, and a Byte64 encoded string of the double feature vector) that can be serialized to a JSON format string.
I use jackson-databind library (https://github.com/FasterXML/jackson-databind) to do the serialization. You will need it on your classpath if you want to use my snippet on the README.
I have added the missing functions and utils into the README. 
Feel free to ask me if you need more clarification!
